name: CLI Deploy
on:
  pull_request:
    paths:
      - packages/**
    branches:
      - main
    types:
      - closed
jobs:
  publish_when_merged:
    if: ${{ github.event.pull_request.merged == true && github.repository_owner == 'billybillydev' && contains(github.event.pull_request.labels.*.name,'cli') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          
      - name: Install Bun
        run: npm install bun

      - name: Install dependencies
        run: npm ci

      - name: Build CLI (for publishing)
        run: npm run build:cli

      - name: Publish CLI
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/cli
